### ISSUE TITLE
开机时的错误提示

### ISSUE THREAD

**Issue by riverscn** [JACK-THINK/Nvidia-Shield-TV-2017-Cookbook#1]
我刷机后，启动时会有错误提示
"Your device is corrupt. It cannot be trusted" 
请问您会有吗？

**Comment by snowleopardw** [comment]
`fastboot oem lock`

**Comment by riverscn** [comment]
fastboot oem lock 做过了。没有oem lock提示的是 Your device is unlocked。所以不是这个引起的……真是奇怪了

**Comment by JACK-THINK** [comment]
1. 你的盒子是NVIDIA SHIELD TV 2017吗？
2. 你下载的固件名称是NVIDIA SHIELD TV 2017 Recovery OS Image  7.0.1 2018/06/13 吗？如果是别的名称，肯定会这样，因为固件不对

**Comment by snowleopardw** [comment]
<img width="1440" alt="2018-06-27 11 58 18" src="https://user-images.githubusercontent.com/7870528/41986148-dbddef4e-7a67-11e8-80ad-cc4668f55386.png">

**Comment by riverscn** [comment]
重新刷机解决了

**Comment by snowleopardw** [comment]
<img width="1439" alt="2018-07-18 2 56 59" src="https://user-images.githubusercontent.com/7870528/42840802-95def80c-8a3a-11e8-9e3b-dec0a2a5be4c.png">
