### ISSUE TITLE
执行fastboot oem unlock时，手柄无响应

### ISSUE THREAD

**Issue by caecity43** [JACK-THINK/Nvidia-Shield-TV-2017-Cookbook#3]
手柄无法按A来confirm，有没有人遇到这个情况？

我重新拔线进系统重新配对也不行。

两天前刷过一台同样的shield tv，过程很顺利，不知道这次是因为什么。

--------------------------

猜测有两个原因可能导致手柄无响应的:

1. 在前一台shield tv刷机完成后，在新系统里，我升级过手柄和遥控器
2. 两次刷机都是在同一台pc上操作的

第1点的可能性最大

**Comment by snowleopardw** [comment]
第二台 Shield TV 自带的手柄呢？

**Comment by caecity43** [comment]
@snowleopardw 忘了回来反馈了，使用第二台的未升级过的手柄顺利刷完了。

但不确定倒底是机器和手柄有绑定关系，还是因为手柄升级过导致的。

另外我在第15步没有执行最后一条`fastboot reboot`，而是直接执行了`fastboot oem lock`，也是能正常刷完的，省掉了中间那几步。

感谢作者把方法整理共享出来。

**Comment by 0neday** [comment]
use keyboard instead of shield controller
