### ISSUE TITLE
请问如何救砖的？

### ISSUE THREAD

**Issue by cool5** [JACK-THINK/Nvidia-Shield-TV-2017-Cookbook#5]
我刷完之后少了一步fastboot oem lock
就重启了。驱动变成了APX
安装了驱动后，设备管理器变成NVIDA USB Boot-recovery driver for Mobile
这时候如何修复？看网上教程需要nvflash刷机

**Comment by cool5** [comment]
nvflash救砖需要某个*.cfg文件用于识别和格式化分区。您能分享一份*.cfg吗？谢谢

**Comment by 0neday** [comment]
press A + B key when reboot shield, this could enter into fastboot mode manually

**Comment by tonyx123** [comment]
有救吗？
