### ISSUE TITLE
23步之前需要进入开发模式

### ISSUE THREAD

**Issue by flipphos** [JACK-THINK/Nvidia-Shield-TV-2017-Cookbook#6]
今天照做了，成功刷入7.2.3版本。使用很爽。plex 4k硬解妥妥的。非常感谢这么详细的教程！

有两点想讨论：
1. 第23步之前，是需要重复前述的步骤进入开发模式的，最好提一下。 另外进入开发模式之后，我碰到了设备管理器中没有设备的情况，需要插拔一下接入pc的usb电缆，即可识别。
2. 第15步的 最后一条指令 fastboot reboot 是否可以先不执行，而直接使用屏幕菜单选择Boot recovery kernel，然后『双清』操作。这样似乎更有希望双清完毕后重启就可以成功引导。最后只要激活后再锁bootloader一步就可以了。

**Comment by JACK-THINK** [comment]
@flipphos 

1. 您提到的第一点非常好，确实是我疏忽了。

2. 这个我不太清楚，这篇教程是我自己刷机过程的复现。您提到的第二点，我没有亲自试过。所以我不敢写入教程。

**Comment by EddardStarko** [comment]
刷错包了…… 楼主知道怎么 APX 模式 救砖吗？
